name: Deploy to EC2

on:
  push:
    branches:
      - main  

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install SSH client
      run: sudo apt-get install -y openssh-client

    - name: Add SSH key
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Deploy to EC2
      run: |
        ssh -o StrictHostKeyChecking=no ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} << 'EOF'
          cd ${{ secrets.EC2_PATH }}
          if [ -d "SmartMove-G2-Backend" ]; then
            rm -rf SmartMove-G2-Backend
          fi
          git clone https://github.com/ezebarrena/SmartMove-G2-Backend.git
          cd SmartMove-G2-Backend/
          export CONNECTION_STRING="${{ secrets.CONNECTION_STRING }}"
          export HOST="${{ secrets.HOST }}"
          export USER="${{ secrets.USER }}"
          export PASS="${{ secrets.PASS }}"
          export SERVICE="${{ secrets.SERVICE }}"
          export PORT="${{ secrets.PORT }}"
          npm install
          pm2 start server.js &> output.log &
        EOF
